sunbird-cb/knowledge-platform

content-api/content-actors/src/main/scala/org/sunbird/content/util/RetireManager.scala
platform-modules/mimetype-manager/src/main/scala/org/sunbird/mimetype/mgr/impl/HtmlMimeTypeMgrImpl.scala

Index validation

---

search-api/search-core/src/main/java/org/sunbird/search/client/ElasticSearchUtil.java
search-api/search-core/src/main/java/org/sunbird/search/processor/SearchProcessor.java

Aggregation on nested fields

---

schemas/asset/1.0/schema.json
schemas/collection/1.0/schema.json
schemas/content/1.0/schema.json

Newfields proposal

---

content-api/content-actors/src/main/scala/org/sunbird/content/util/RetireManager.scala
content-api/content-service/app/controllers/BaseController.scala
content-api/content-service/conf/application.conf
platform-modules/mimetype-manager/src/main/scala/org/sunbird/mimetype/mgr/impl/HtmlMimeTypeMgrImpl.scala
schemas/asset/1.0/schema.json
schemas/collection/1.0/schema.json
schemas/content/1.0/schema.json
schemas/question/1.0/schema.json
schemas/questionset/1.0/schema.json
search-api/search-actors/src/main/java/org/sunbird/actors/SearchActor.java
search-api/search-core/src/main/java/org/sunbird/search/client/ElasticSearchUtil.java
search-api/search-core/src/main/java/org/sunbird/search/dto/SearchDTO.java
search-api/search-core/src/main/java/org/sunbird/search/processor/SearchProcessor.java

Release-4.9 upgrade

---

content-api/content-service/app/controllers/BaseController.scala
content-api/content-service/conf/application.conf

Configuration param for timeout

---

content-api/content-actors/src/main/scala/org/sunbird/content/util/RetireManager.scala

**Please** include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Reverted the changes

---

content-api/content-service/conf/application.conf
platform-modules/mimetype-manager/src/main/scala/org/sunbird/mimetype/mgr/impl/HtmlMimeTypeMgrImpl.scala

Index file validation

---

content-api/hierarchy-manager/src/main/scala/org/sunbird/managers/UpdateHierarchyManager.scala

Cbrelease 4.0.1 hierarchy issue

---

content-api/hierarchy-manager/src/main/scala/org/sunbird/managers/UpdateHierarchyManager.scala

Hierarchy update logs

---

content-api/content-service/conf/application.conf
content-api/hierarchy-manager/src/main/scala/org/sunbird/managers/UpdateHierarchyManager.scala

Hierarchy update fix

---

content-api/content-service/conf/application.conf
content-api/hierarchy-manager/src/main/scala/org/sunbird/managers/UpdateHierarchyManager.scala

hierarchy fix

---

content-api/content-actors/src/main/scala/org/sunbird/content/util/RetireManager.scala

updateNodesToRetire changes

---

content-api/hierarchy-manager/src/main/scala/org/sunbird/managers/HierarchyManager.scala
ontology-engine/graph-core_2.11/src/main/scala/org/sunbird/graph/external/ExternalPropsManager.scala

Hierarchy impl logs

---

search-api/search-core/src/main/java/org/sunbird/search/processor/SearchProcessor.java

implemented fuzzy logic to the search

---

search-api/search-core/src/main/java/org/sunbird/search/processor/SearchProcessor.java

added the fuzzy logic to the search

---

content-api/content-actors/src/main/scala/org/sunbird/content/util/CopyManager.scala
content-api/content-service/conf/application.conf

'
* Hardware versions: 2 CPU/ 4GB RAM

Copy content artifacturl must not included bug

---

content-api/content-actors/src/main/scala/org/sunbird/content/util/CopyManager.scala
content-api/content-service/conf/application.conf

* Hardware versions: 2 CPU/ 4GB RAM

Cbrelease 4.0.1 artifacturl bug fix

---

search-api/search-service/app/controllers/SearchController.scala

* Hardware versions: 2 CPU/ 4GB RAM

Removed channel.isEmpty and added channel.isBlack

---

search-api/search-core/src/main/java/org/sunbird/search/processor/SearchProcessor.java
search-api/search-service/conf/application.conf

Introduced new flag and changes to make fuzzy search mandatory when no results

Introduced new flag to use fuzzy upon zero results

---

search-api/search-core/src/main/java/org/sunbird/search/processor/SearchProcessor.java

* Hardware versions: 2 CPU/ 4GB RAM

4.8.0 search fix v2
